### ISSUE TITLE
Response should be done by an io.Writer rather than returning interface{}

### ISSUE THREAD

**Issue by h12w** [eawsy/aws-lambda-go#13]
It is idiomatic to use an io.Writer in Go, and it is too restrictive to assume the result in JSON format.

**Comment by fsenart** [comment]
We have two constraints in this project:
1. Follow as closest as possible, Go idioms  
     Because we should not upset existing Go users accustomed with community-wide best practices.
2. Follow as closest as possible, existing official AWS runtime interfaces  
     Because we should provide a smooth way for this project's users to migrate to the future official support of Go by AWS. 

In the intersection of these two constraints, discussions reside and decisions must be made. We have chosen to support AWS idioms over Go idioms for the simple reason that in the microservices world of Lambda, language heterogeneity is the king and so is interface uniformity across these languages. 

Concretely, in the official [Lambda programming model](http://docs.aws.amazon.com/lambda/latest/dg/programming-model-v2.html), handlers return "objects" and not "buffers/readers". Translated into the Go world, `interface{}` is the most permissive/idiomatic way to achieve the above uniformity.

**Comment by h12w** [comment]
It makes sense. Thanks for your explanation, then it is Lambda too restrictive :-)
