### ISSUE TITLE
Building on MacOS X

### ISSUE THREAD

**Issue by edasque** [eawsy/aws-lambda-go#4]
Can you give us some guidance on how you'd use build on MacOS X? I am guessing you'd use the Docker image highlighted but there aren't any volumes shared or example command to run the build and be able to access the output.

**Comment by fsenart** [comment]
Hi,

We've added a few [more examples](https://github.com/eawsy/aws-lambda-go/tree/master/_example) yesterday and tried to [clarify](https://github.com/eawsy/aws-lambda-go/commit/c2c51385f45064d638b2b965bd4cbfb0df314a0c) how OSX users should build them.

To recap for OSX users:
- You **MUST** use the provided docker container to build
- You **SHOULD** use the `dbuild` and `dpack` targets of examples Makefiles.

Is it ok for you?
