### ISSUE TITLE
Missing setup instructions

### ISSUE THREAD

**Issue by inge4pres** [eawsy/aws-lambda-go#7]
Hi,

when reading the docs it seems that the docker entrypoint is already present.
I believe the correct setup is 
`cd eawsy/aws-lambda-go/_docker && go build entrypoint.go && docker build -t eawsy/aws-lamdba-go  .` but this is not clear from wiki/README.

**Comment by fsenart** [comment]
Hi,

You don't need to build the Docker image, it has been already built by us and provided on Docker Hub at [eawsy/aws-lambda-go](https://hub.docker.com/r/eawsy/aws-lambda-go/). Also, there is nothing to setup, you can already build your projects with [default options](https://github.com/eawsy/aws-lambda-go/wiki/Deployment%20Package#default) or [custom ones](https://github.com/eawsy/aws-lambda-go/wiki/Deployment%20Package#custom).

**Comment by inge4pres** [comment]
Hi, sorry for not replying till now, pulled the image and it's working great!
Thank you

**Comment by fsenart** [comment]
You're welcome :smirk:
