### ISSUE TITLE
Unit tests depend on cgo and python

### ISSUE THREAD

**Issue by Zambiorix** [eawsy/aws-lambda-go#9]
Hi guys,

This package is golden! Just what I have been looking for!

I threw out all my node.js code and have written a single aws lambda in go that takes care of all my AWS API Gateway routes. Combined with the official AWS Go SDK, and you have an api backend that is blazing fast, yet ZERO maintenance ... just WOW!

I would suggest only minor changes to split the package in 2 parts:

I have created an api-package that will handle all incoming requests from the lambda handler, with no dependencies on aws-lambda-go itself, because I want it to be used in a test app on my mac, as well as in the final deployment package. Building the deployment on my mac and then submitting it to AWS is too slow for testing.
I have created the deployment package with aws-lambda-go & my api-package dependencies and forward all lambda handler calls to my api, with the event and context data. That works great (slow build, but that is ok for deployments)
I have created a mac test application with my api-package dependency and route all kinds of test calls to my api with dummy event & context data to quickly test my api.
The problem with this scenario is context.go. I need it in my api-package and mac application without all the other code (that won't compile in a mac environment -> I don't want to install all the needed dependencies that you use in the docker image)

Currently context.go is in:
github.com/eawsy/aws-lambda-go/service/lambda/runtime

If you would put it in:
github.com/eawsy/aws-lambda-go/service/lambda/context

.. then all would be perfect for me, I can add it to my api-package and mac test application without all the other code. The imports need to be updated of course, but that is not breaking I assume.

Hope it make sense?

Thanks!
Gerd

Ps. where do I send the keg of beer?

**Comment by fsenart** [comment]
Hi @Zambiorix 

First of all, let me thank you for your issue title "awesome package". It's an awesome title :+1: 
I really appreciate your enthusiasm.

We will review the impact of the changes you need, and come back asap to support you in your developments. 

PS: If you are passing through Strasbourg, France (anytime) ping us to have a drink together ;)

**Comment by Zambiorix** [comment]
I hardly ever use "awesome", because I hear it so often that is has lost it's meaning. But this time it is deserved! Hey, I'll say it again.. awesome package! :-)

Oh and by: ~~my mac~~, i mean my development machine 
I should hide my personal preferences better :-)

I'm also using my own adapted docker image to keep the tmp build files out of my source tree:

```

FROM golang:latest

ADD . /go/src/bitbucket.org/lambda-compiler

RUN \
  apt-get update \
  && apt-get install -y --no-install-recommends pkg-config python-dev zip \
  && rm -rf /var/lib/apt/lists/* \
  && go install bitbucket.org/lambda-compiler \
  && mv /go/bin/lambda-compiler ~

WORKDIR /tmp/lambda-compiler

ENTRYPOINT ~/lambda-compiler


```

and have separate build and run steps to speed up the final build process

```

docker build --rm -t "aws-lambda-go-compiler" .

```

... and build a deployment package

```

NAME="aws-lambda-go-compiler"
docker run --rm -a stdin -a stdout -i -t -v "$GOPATH:/go" -v "$PWD:/tmp/lambda-compiler" --name "$NAME" "$NAME"


```

**EDIT**:
In entrypoint.go I've added some extra code to have cli kinda features. I build my docker image once, then run it and give it build/package/quit commands at will .. can implement publish to aws-lambda too, .. 

Cheers
Gerd

**Comment by fsenart** [comment]
@Zambiorix can you please fork the project, commit the changes and show me how refactoring the context package can help you?

I tried to overcome your problem but it seems that context.RemainingTimeInMillis will still be a problem. By working on your fork I can better understand your problem.

**Comment by lion3ls** [comment]
Hi @Zambiorix,

First of all, thank you for you awesome support :+1: 

But let me ask you, do you use API Gateway with [{Proxy+}](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html) and [aws-lambda-go-net](https://github.com/eawsy/aws-lambda-go-net) for your project ? If not it worth a try, it enables you to use standard HTTP web frameworks (ServeMux, Gin, Gorilla, and more).

**Comment by Zambiorix** [comment]
Hi @fsenart 

I have forked your project and made it work in my project with a decoupled context object:
[Zambiorix/aws-lambda-go](https://github.com/Zambiorix/aws-lambda-go)

I solved the context.RemainingTimeInMillis issue by replacing it with a callback. You could also change the concept by not serving the context object itself but an interface. That way future changes are imho easier to implement. Especially if you add functions..

Cheers
Gerd

**Comment by Zambiorix** [comment]
Hi @lsuss 

I am aware of aws-lambda-go-net, but I am trying to avoid as much middleware as possible (especially an extra net server & mux). I'm currently using proxy+ and aws-lambda-go with my own layer in between.

Thanks for mentioning!!

Cheers
Gerd

**Comment by fsenart** [comment]
@Zambiorix I found that the callback solution for RemainingTimeInMillis is a great idea and then retain it. 

But in order to maintain compatibility with AWS Lambda official packages structure and naming (for example (https://github.com/aws/aws-lambda-java-libs) I don't think that it's a good idea to separate the Context into its own package. Its semantic is closely related and embedded into the runtime.
Your issue with testing can be resolved with go build tags and I've made the pull request in this sense. Please try this new solution and see if it can do the job.
The only thing you need when testing is to disable CGO by setting CGO_ENABLED environment variable to 0 (as described in the PR comment).

@vancluever @cristim can you please test the PR with your current projects for validation. Thx.

**Comment by fsenart** [comment]
@Zambiorix I've resolved yesterday problem by using custom tags instead of official tags. Now you have the same benefit but without compromising packages which still need cgo.

To build your project (in the meantime of merging the PR into the main repo and updating the Docker image) you need to change the build by appending `-tags proxy` to the command line.
You can achieve this in two ways.
You create a custom Docker image and change the [entrypoint](https://github.com/eawsy/aws-lambda-go/blob/master/_docker/entrypoint.go#L38) as follows:

``` go
cmd := exec.Command("go", "build", "-buildmode=c-shared", "-ldflags=-w -s", "-tags", "proxy", "-o", so)
```

or you log into the docker image directly and make your build manually:

``` sh
docker run --rm -v $GOPATH:/go -v $PWD:/tmp -it --entrypoint bash eawsy/aws-lambda-go
go build -buildmode=c-shared -ldflags='-w -s' -tags proxy -o handler.so
zip handler.zip handler.go
```

After merging the PR and updating the Docker image there is nothing special todo.

**Comment by fsenart** [comment]
@Zambiorix sorry for your awesome issue title but it has to be more relevant now :smiley:

**Comment by Zambiorix** [comment]
No worries, despite the title, the package is STILL awesome :-)

**Comment by fsenart** [comment]
@Zambiorix any news? Have you tried the PR? If it's ok for you please make a PR back to this repo, so that I can merge it in master.

**Comment by fsenart** [comment]
@Zambiorix Great job ;) I will announce changes in the Gitter. You may do a `docker pull` so everything is updated as I refreshed the Docker hub image.

**Comment by Zambiorix** [comment]
All is working now! Thanks again for such an "awesome" package :-)

Cheers!
